[package]
name = "jonah"
version = "0.1.0"
edition = "2021"

[dependencies]
bollard = "0.18.1"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
toml = "0.8"
futures-util = "0.3"
anyhow = "1.0.95"
