docker = "./Dockerfile"

exports = [
    { path = "/build/target/x86_64-unknown-linux-musl/release/jonah", name = "jonah-linux-x86_64" },
    { path = "/build/target/aarch64-unknown-linux-musl/release/jonah", name = "jonah-linux-aarch64" },
    { path = "/build/target/x86_64-pc-windows-gnu/release/jonah.exe", name = "jonah-windows-x86_64.exe" },
    { path = "/build/target/x86_64-apple-darwin/release/jonah", name = "jonah-macos-x86_64" },
    { path = "/build/target/aarch64-apple-darwin/release/jonah", name = "jonah-macos-aarch64" },
]
