git_base = "https://github.com/eelias13/"

[[projects]]
rel_git = "open-gal"
build_file = "editor/jonah_build.toml"
out_path = "open-gal"

[[projects]]
rel_git = "open-gal"
build_file = "cli/jonah_build.toml"
out_path = "open-gal/cli"


# [[projects]]
# rel_git = "astro-spotlight"
# build_file = "jonah_build.toml"
# out_path = "."
# 
# [[projects]]
# rel_git = "func-checker"
# build_file = "jonah_build.toml"
# out_path = "func-checker"
# 