name: Release

on:
  push:
    tags:
      - "v*.*.*"  # Trigger on version tags (e.g., v1.0.0)
permissions:
  contents: write  # Allows creating releases & modifying repository contents
  packages: write  # Allows publishing Rust crates, npm, Docker images, etc.
  issues: write    # Allows opening & modifying issues
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build project
        run: cargo build --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/jonah
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
